# Generated by Django 2.1.1 on 2018-09-01 18:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Stomach',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField()),
                ('consistency', models.CharField(choices=[('OK', 'OK'), ('QMUSHY', 'Quite mushy'), ('RMUSHY', 'Really mushy'), ('DIARRHEA', 'Full-on diarrhea')], max_length=255)),
                ('bloodiness', models.CharField(choices=[('NONE', 'None'), ('BLOT', 'Lots of bright blood'), ('BSOME', 'Some bright blood'), ('DLOT', 'Lots of dark blood'), ('DSOME', 'Some dark blood'), ('MLOT', 'Lots of blood, hard to say if it is dark or bright'), ('MSOME', 'Some blood, hard to say if it is dark or bright')], max_length=255)),
                ('comment', models.TextField(null=True)),
                ('user', models.ForeignKey(limit_choices_to={'is_current_user': True}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
