# Generated by Django 2.1.1 on 2018-09-02 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0002_auto_20180902_0825'),
    ]

    operations = [
        migrations.AlterField(
            model_name='edible',
            name='ingredients',
            field=models.ManyToManyField(blank=True, related_name='_edible_ingredients_+', to='records.Edible'),
        ),
    ]
